# available directory themes:
# spearmint, peppermint, hemingway, brookmint
theme = 'spearmint'

[general]
title = "TheShieldIT"
logo = ""
iconLogo = "tabler:coffee"

[general.seo]
name = "TheShieldIT"
description = "Find the best security and privacy tools for your needs"
url = "https://thesheildit.com"

[directoryData.source]
name = "json"    # default, mock, sheets, json
links = "normal"

[directoryData.tagPages]
title = "{0} Apps"

[directoryData.search]
placeholder = "Search among {0} listings of this directory :)"

[[directoryData.tags]]
key = "browser"
name = "Browser"
color = "orange"
emoji = "🛜"
description = "List of the best browsers across all platforms"

[[directoryData.tags]]
key = "password manager"
name = "Password Manager"
color = "green"
emoji = "🔑"
description = "List of the best password managers across all platforms"

[[directoryData.tags]]
key = "2FA"
name = "2FA"
color = "purple"
emoji = "🔒"
description = "2FA (Two-Factor Authentication) is a security method that requires two forms of verification—typically a password and a secondary code—to access an account."

[[directoryData.tags]]
key = "Encrypted Mail"
name = "Encrypted Mail"
color = "red"
emoji = "✉️"
description = "Encrypted email to protect your everyday"

[[directoryData.tags]]
key = "DNS"
name = "DNS"
color = "green"
emoji = "☁️"
description = "DNS (Domain Name System) is the internet’s address book, translating human-readable domain names like example.com into IP addresses that computers use to communicate."

[header.banner]
show = true
text = "Join Us On Discord"
link = "https://discord.gg/3wEDKtCyNR"
brandText = ""

[header.navbar]
colorModeSelector = true

[[header.navbar.links]]
name = "Blog"
href = "/blog"

[[header.navbar.links]]
name = "Analytics"
href = "https://us.posthog.com/shared/vHlGCcSqPjGH4r_QijaXSETtmN9J-g"
target = "_blank"

[header.actionButton]
text = "Submit an app"
href = "https://tally.so"

[footer]
description = "Best directory for my niche."

[footer.socials.x]
link = "https://x.com/mark_bruderer"

[footer.socials.youtube]
link = "https://www.youtube.com/@mark_hacks"
